#!/bin/bash

INTERFACE1="ens8f0"
INTERFACE2="ens9"
INTERFACE3="ens10"

ip addr add 200.200.200.2/30 dev $INTERFACE1
ip link set $INTERFACE1 up
ip addr add 200.200.201.1/30 dev $INTERFACE2
ip link set $INTERFACE2 up
ip addr add 10.10.2.1/28 dev $INTERFACE3
ip link set $INTERFACE3 up

sysctl -w net.ipv4.ip_forward=1
ip route add 200.200.202.0/30 via 200.200.201.2 dev ens9
ip route add 200.200.204.0/30 via 200.200.201.2 dev ens9

ip route add 10.10.1.0/27 via 200.200.200.1 dev ens8f0
ip route add 10.10.3.0/26 via 200.200.201.2 dev ens9
ip route add 10.10.4.0/29 via 200.200.201.2 dev ens9
ip route add 10.10.5.0/26 via 200.200.201.2 dev ens9

#FILTERING NEW TRAFFIC
iptables -A FORWARD -i ens10 -s 10.10.2.2 -d 10.10.1.2 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i ens10 -s 10.10.2.2 -d 10.10.1.3 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i ens10 -s 10.10.2.2 -d 10.10.1.4 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i ens10 -s 10.10.2.3 -d 10.10.1.2 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i ens10 -s 10.10.2.3 -d 10.10.1.3 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i ens10 -s 10.10.2.3 -d 10.10.1.4 -m state --state NEW,ESTABLISHED -j ACCEPT

iptables -A FORWARD -i ens10 -s 10.10.2.3 -d 10.10.4.2 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i ens10 -s 10.10.2.3 -d 10.10.4.3 -m state --state NEW,ESTABLISHED -j ACCEPT

#FILTERING RELATED TRAFFIC
iptables -A FORWARD -i ens10 -d 10.10.1.2 -s 10.10.2.2 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i ens10 -d 10.10.1.3 -s 10.10.2.2 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i ens10 -d 10.10.1.4 -s 10.10.2.2 -m state --state ESTABLISHED,RELATED -j ACCEPT

iptables -A FORWARD -i ens10 -d 10.10.4.2 -s 10.10.2.4 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i ens10 -d 10.10.4.4 -s 10.10.2.4 -m state --state ESTABLISHED,RELATED -j ACCEPT

#DROP TRAFFIC
iptables -A FORWARD -i ens10 -j DROP
