#!/bin/bash

INTERFACE1="ens8f0"
INTERFACE2="ens9"
INTERFACE3="ens10"

ip addr add 200.200.201.2/30 dev $INTERFACE1
ip link set $INTERFACE1 up
ip addr add 200.200.202.1/30 dev $INTERFACE2
ip link set $INTERFACE2 up
ip addr add 10.10.3.1/26 dev $INTERFACE3
ip link set $INTERFACE3 up

sysctl -w net.ipv4.ip_forward=1
ip route add 200.200.200.0/30 via 200.200.201.1 dev ens8f0
ip route add 200.200.204.0/30 via 200.200.202.2 dev ens9

